Forest UI and pause menu
henriksen-marcus/Moose-Gamification pull request #60
Opened 2023-04-15 14:07 UTC by Aleksthor

2023-04-16 15:49 UTC, henriksen-marcus requested changes
### Forest.cs 
**Linje 282-336:** Bruk switch statement. Denne koden blir fryktelig treig jo yngre et tre er.
**Linje 555:** Her mangler det nok en *else*. Du kaller flere ganger på GetSelectedForest her. Du kan også gjøre switchene mye enklere, f.eks:
```csharp
var mesh = go.transform.Find("Stem").Find("Leaves").GetComponent<MeshRenderer>();
mesh.material = forestType switch
{
      ForestType.Birch => normalBirch,
      ForestType.Spruce => normalSpruce,
      ForestType.Pine => normalPine    
};
```
### ElgMatingSeason.cs
Her bør `mScript.GetComponent<NavMeshAgent>()` lagres i en variabel.

### Pausemenu.cs
Ikke sjekk for keydown i tick. Vi bruker Unity sitt nye input system, benytt "Pause" funksjonen i Camera_v2 som allerede er satt opp. Evt kan du bruke samme metode som jeg gjorde ved å sette opp input events i camera ved å binde funksjoner til eventene i `InputProvider.cs` som jeg har laget.

2023-04-17 16:19 UTC, Aleksthor commented
Da er endringene gjort :)

2023-04-17 16:25 UTC, Aleksthor commented
Conflict dukket opp etter siste push, men det er bare å overskrive

2023-04-17 19:24 UTC, henriksen-marcus approved these changes

2023-04-17 19:25 UTC, merged