Merged the UI's and rescaled all UI elements
henriksen-marcus/Moose-Gamification pull request #63
Opened 2023-04-22 23:39 UTC by Aleksthor

2023-04-22 23:48 UTC, henriksen-marcus requested changes
Ser ut som vi har et problem med scaling her: 

![2023-04-23 01_43_57](https://user-images.githubusercontent.com/89453098/233812144-a49e62f8-34c1-43f3-b649-296226be187a.png)

2023-04-23 20:20 UTC, henriksen-marcus requested changes
Overlapping issue, må scale ned vinduet på bunnen, den tar opp nesten 1/4 av skjermen



![image](https://user-images.githubusercontent.com/89453098/233863804-b821005f-93e8-4386-8c19-970393787e4c.png)

2023-04-23 20:24 UTC, Aleksthor commented
Nice, rescalet den. Mye små ting når man endrer alt på engang ^^

2023-04-23 20:26 UTC, Aleksthor commented
![image](https://user-images.githubusercontent.com/89393939/233864253-ba2c38b9-e025-49d0-b5ad-8edff7681c34.png)

2023-04-23 20:34 UTC, Aleksthor commented
Merged in the standalone file browser since it worked well. 
Also heres the project icon

![image](https://user-images.githubusercontent.com/89393939/233864794-161ccdfc-9b24-4d9e-b2c7-8f8801cceb0d.png)


Im done now, unless u have anything else :)

2023-04-23 23:00 UTC, henriksen-marcus approved these changes

2023-04-23 23:02 UTC, merged